[project]
name = "orjsonic"
version = "0.1.1"
description = "A fleixible and fast wrapper around orjson for custom JSON encoding/decoding"
readme = "README.md"
requires-python = ">=3.10"
license-files = ["LICENSE"]
authors = [{ name = "randomseed42", email = "randomseed42@protonmail.com" }]
keywords = ["json", "orjson", "custom", "encoding", "decoding"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3",
  "Topic :: Software Development :: Libraries",
]
dependencies = ["numpy", "orjson"]

[project.urls]
Homepage = "https://github.com/randomseed42/orjsonic"
